// Copyright 2021-2026 @polkadot/app-laws authors & contributors
// SPDX-License-Identifier: Apache-2.0

export const MATH_DISPLAY_REQUIREMENTS_PROMPT = String.raw`Math display requirements:
- Fractions: whenever a mathematical fraction is written or displayed, use LaTeX fraction notation \frac{a}{b} (with the actual numerator and denominator substituted), never slash notation such as a/b. In JSON strings, escape the LaTeX backslash so the JSON remains valid (for example, \\frac{a}{b}); in TikZ labels, render \frac{...}{...} in TeX math mode.
- Number lines: a number line is a straight line with equally spaced ticks, with numbers shown below the ticks, 0 and 1 always labeled, and exactly one arrow indicating the positive direction. The number line always has one extra step between the last tick mark and the arrow. Do not use arrowheads at both ends and do not omit the positive-direction arrow.`;

export const EXERCISE_TEMPLATE_STYLE_PROMPT = `Write every generated exercise as the short concrete instance of a reusable template pattern. Include only enough concrete variable context so the same wording pattern can later be reused by changing 1-3 data-bearing words or values while keeping the instruction, operation, structure, input/output types, and solution method unchanged. Make those replaceable data slots obvious from the concrete wording. This is a structural requirement only: do not generate, propose, compare, or output extra alternate or variant exercises to demonstrate the pattern; output only the exercise or exercises explicitly required by the calling prompt.

Keep learner-facing task text short and direct. Do not include solution steps, construction details that disclose answer-bearing information, or tutorial prose in the question unless carrying out that procedure is itself the target skill. Keep the solution concise, but make the solving method visible whenever the answer is not immediately obvious. For a one-step or self-evident task, the result plus the direct substitution, rule application, or calculation is enough. For a non-obvious or multi-step task, include the essential steps in logical order, with the intermediate calculations, transformations, or reasons needed to understand how the final answer is reached. Do not skip a meaningful transition merely to shorten the solution, and do not add tutorial filler beyond the steps needed to solve the specific exercise. Templatability, self-containment, and an unambiguous learner operation take priority over the word target.`;

export const LEARNER_AGE_PROMPT = (learnerAge?: number): string => Number.isSafeInteger(learnerAge)
  ? `The current learner age is ${learnerAge} years. Keep vocabulary, sentence complexity, assumed background knowledge, cognitive load, examples, task difficulty, answer expectations, and any visual content appropriate for a ${learnerAge}-year-old learner. Preserve the intended learning target and required method; age-appropriateness must not simplify away the skill being taught or assessed.`
  : '';

export const EXERCISE_QUESTION_BREVITY_PROMPT = `Make each Exercise description a succinct learner-facing question or command. Prefer one short sentence. Aim for about 6-16 words and normally no more than about 20 words; exceed that only when essential task data or constraints cannot be omitted without making the task ambiguous or incomplete. Remove scene-setting, repeated directions, procedural coaching, definitions, and facts already supplied by the concept or a required visual. If a question visual carries task data, refer to it briefly (for example, "the figure" or "the visual") instead of restating its contents. Brevity must never remove values, conditions, units, or other information the learner actually needs to answer.`;

export const EXERCISE_NON_BINARY_RESPONSE_PROMPT = `Never generate a yes/no Exercise or any equivalent binary-response task. This prohibition includes prompts answerable only by yes/no, true/false, correct/incorrect, right/wrong, does/does not, can/cannot, or another two-choice confirmation. Every Exercise must require the learner to produce substantive answer content beyond a binary judgment, such as a value, word or phrase, calculation, transformation, construction, correction, classification with the requested category supplied by the learner, or an explanation/reason when that is the target skill. If the source concept is naturally phrased as a binary check, preserve the same learning target but rewrite the task so the learner must demonstrate the knowledge directly rather than merely confirm or deny a statement. Do not evade this rule by replacing yes/no with another two-option wording.`;
